### ISSUE TITLE
Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by slorber** [HubSpot/tooltip#33]
```
Uncaught TypeError: Cannot read property 'classList' of null tooltip.js:1661
hasClass tooltip.js:1661
DropInstance.isOpened tooltip.js:3138
DropInstance.close tooltip.js:3176(anonymous function)
```

This happens sometimes

**Comment by geekjuice** [comment]
Thanks for using `Tooltip`. I believe this issue should be resolved with the most recent version of `Tooltip` that was just released. From my experience, this happened when there were either multiple versions of `Tether` or `Drop` included. We have since moved away from bundled versions, so you should only be requiring both `Tether` and `Drop` once. However, if this is still an issue, it'd be great if you could create a jsFiddle or Codepen to show us the issue and I'll be more than happy to help out. :smile_cat:

**Comment by slorber** [comment]
@geekjuice the problem is still here but the stacktrace has changed a little it seems.

```
Uncaught TypeError: 
Cannot read property 'classList' of null tether.js:199 
addClass tether.js:199
(anonymous function) drop.js:40
```

The line seems:
```
        setTimeout(function () {
          addClass(_this4.drop, '' + drop.classPrefix + '-after-open');
        });
```

The tooltip works fine but it's just annoying to have this logged oftenly :)

**Comment by geekjuice** [comment]
Hmm, would it possible to create an example of this issue through jsFiddle or similar? Trying to wrap my head around why just that instance of `drop` would be `undefined` when the lines right above that use `addClass` on the same reference correctly.

**Comment by slorber** [comment]
unfortunately it is deeply integrated in my ReactJS project and hard to reproduce in a sandbox.

It may be possible that I setup tethertooltip and then remove the dom node directly after (synchronously)
This way the setTimeout will try to add a class on a dom node that doesn't exist anymore.

This is a corner case but I think you should still handle it, as well as I should find in my app why I would setup a tooltip and remove the node just behind...

**Comment by geekjuice** [comment]
Ah. Now this [Pull Request](https://github.com/HubSpot/drop/pull/58) in `Drop` makes more sense. It stills like a hack, but I think for the time being, checking for the existence of the drop instance and only then adding the class makes sense. I'll that fix soon

**Comment by slorber** [comment]
yes that seems to be :)

**Comment by slorber** [comment]
@geekjuice is this fixed in new releases?

**Comment by geekjuice** [comment]
@slorber Yup, it was fixed in `drop` [here](https://github.com/HubSpot/drop/pull/77). As long as your version of `drop` is `>1.0.6`, you should no longer see all the logging. 

If that's not the case though, let me know and I'll take another look.

**Comment by slorber** [comment]
ok thanks i've upgraded the lib and will let you know if there are errors
